### ISSUE TITLE
Add a ReadOnly option to Client.login()

### ISSUE THREAD

**Issue by jamiereid** [seiruss/cp_api#2]
The Management API on the Checkpoints will only return a `uid` if the session is opened with read permissions. This is not always desirable to do. (I use an account with read only permissions where possible).

I propose adding a `readonly` flag/option to Client.login(), or perhaps changing `UID` to be an Option<>?

Seeking thoughts / advice on this feature, and the way (if any) you'd best like it implemented.
Happy to make an attempt and raise a PR after discussion.

**Comment by seiruss** [comment]
Added the read only option to the client. I'll test it tomorrow and make sure it works.

**Comment by seiruss** [comment]
Testing is successful. The default for read only will be false to match the Management API.

Going to add continue-last-session as well.

**Comment by seiruss** [comment]
Published read only in v0.3.1

**Comment by jamiereid** [comment]
Awesome, thank you!
